"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useSearchParams, useRouter } from "next/navigation";
import { problemApi } from "@/lib/api";
import { EmptyState, PageHeader } from "@/components/ui-kit";
import { toast } from "sonner";
import { useState } from "react";
import { useForm } from "@tanstack/react-form";
import { z } from "zod";

export default function ProblemsPage() {
  const [creating, setCreating] = useState(false);
  const params = useSearchParams(); const router = useRouter(); const client = useQueryClient();
  const search = params.get("search") ?? ""; const type = params.get("type") ?? "";
  const query = useQuery({ queryKey: ["problems", search, type], queryFn: () => problemApi.list({ page: Number(params.get("page") ?? 1), limit: 30, ...(search && { search }), ...(type && { type }) }) });
  const remove = useMutation({ mutationFn: problemApi.remove, onSuccess: () => { toast.success("Problem deleted"); void client.invalidateQueries({ queryKey: ["problems"] }); } });
  const create = useMutation({ mutationFn: problemApi.create, onSuccess: () => { toast.success("Problem created"); setCreating(false); void client.invalidateQueries({ queryKey: ["problems"] }); }, onError: () => toast.error("Could not create problem") });
  const form = useForm({ defaultValues: { title: "", question: "", optionA: "", optionB: "", correctAnswer: "", points: 10 }, onSubmit: async ({ value }) => { const parsed = z.object({ title: z.string().min(3), question: z.string().min(1), optionA: z.string().min(1), optionB: z.string().min(1), correctAnswer: z.string().min(1), points: z.number().int().min(1) }).safeParse(value); if (!parsed.success) return toast.error("Complete all problem fields"); if (![parsed.data.optionA, parsed.data.optionB].includes(parsed.data.correctAnswer)) return toast.error("Correct answer must match an option"); await create.mutateAsync({ title: parsed.data.title, question: parsed.data.question, type: "MCQ", options: [parsed.data.optionA, parsed.data.optionB], correctAnswer: parsed.data.correctAnswer, points: parsed.data.points }); } });
  const set = (key: string, value: string) => { const next = new URLSearchParams(params); if (value) { next.set(key, value); } else { next.delete(key); } router.replace(`/provider/problems?${next}`); };
  return <main className="p-5 sm:p-10"><PageHeader eyebrow="Authoring" title="Problem library" description="Create and maintain reusable questions for your assessments." action={<button onClick={() => setCreating((value) => !value)} className="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white">{creating ? "Close form" : "New problem"}</button>} />
    {creating && <form onSubmit={(e) => { e.preventDefault(); void form.handleSubmit(); }} className="mb-6 grid gap-4 rounded-2xl border bg-white p-6 md:grid-cols-2"><h2 className="md:col-span-2 text-lg font-black">Create multiple-choice problem</h2>{(["title", "question", "optionA", "optionB", "correctAnswer"] as const).map((name) => <form.Field name={name} key={name}>{(field) => <label className="block text-sm font-bold">{name === "title" ? "Title" : name === "question" ? "Question" : name === "correctAnswer" ? "Correct answer" : `Option ${name.slice(-1)}`}<input value={field.state.value} onChange={(e) => field.handleChange(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3" /></label>}</form.Field>)}<form.Field name="points">{(field) => <label className="block text-sm font-bold">Points<input type="number" value={field.state.value} onChange={(e) => field.handleChange(Number(e.target.value))} className="mt-2 w-full rounded-xl border px-4 py-3" /></label>}</form.Field><div className="md:col-span-2"><button disabled={create.isPending} className="rounded-xl bg-slate-950 px-5 py-3 font-bold text-white">Create problem</button></div></form>}
    <div className="mb-6 flex flex-wrap gap-3"><input value={search} onChange={(e) => set("search", e.target.value)} className="rounded-xl border bg-white px-4 py-3" placeholder="Search questions" /><select value={type} onChange={(e) => set("type", e.target.value)} className="rounded-xl border bg-white px-4 py-3"><option value="">All types</option><option value="MCQ">Multiple choice</option><option value="WRITTEN">Written</option></select></div>
    {query.data?.problems?.length ? <div className="grid gap-4 md:grid-cols-2">{query.data.problems.map((problem) => <article className="rounded-2xl border bg-white p-5" key={problem.id}><div className="flex justify-between gap-4"><h2 className="font-black">{problem.title}</h2><span className="text-xs font-bold text-indigo-600">{problem.type}</span></div><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-500">{problem.question}</p><div className="mt-5 flex items-center justify-between text-xs text-slate-400"><span>{problem.points} points</span><button onClick={() => remove.mutate(problem.id)} className="font-bold text-rose-600">Delete</button></div></article>)}</div> : <EmptyState title="Your library is empty" message="Create a problem to reuse it across multiple assessments." />}
  </main>;
}
