"use client";
import { useQuery } from "@tanstack/react-query";
import { adminApi } from "@/lib/api";
import { EmptyState, PageHeader } from "@/components/ui-kit";

export default function AdminReportsPage() {
  const query = useQuery({ queryKey: ["admin-audit-logs"], queryFn: () => adminApi.logs({ page: 1, limit: 50 }) });
  const logs = query.data?.logs ?? [];
  return <main className="p-5 sm:p-10"><PageHeader eyebrow="Governance" title="Audit reports" description="A transparent record of security-sensitive actions across the platform." />
    <section className="overflow-hidden rounded-2xl border bg-white">{query.isLoading ? <div className="space-y-4 p-6">{[1, 2, 3, 4].map((i) => <div className="h-12 animate-pulse rounded-xl bg-slate-100" key={i} />)}</div> : logs.length === 0 ? <EmptyState title="No audit activity yet" message="Events generated by the API will appear here." /> : <div className="divide-y">{logs.map((log, index) => <div className="flex flex-wrap items-center justify-between gap-4 p-5" key={String(log.id ?? index)}><div><p className="font-bold">{String(log.action ?? "Platform event")}</p><p className="mt-1 text-sm text-slate-500">{String(log.entity ?? "System")} · {String(log.actorId ?? "System actor")}</p></div><time className="text-xs text-slate-400">{log.createdAt ? new Date(String(log.createdAt)).toLocaleString() : "Recent"}</time></div>)}</div>}</section>
  </main>;
}
